# Generated by Django 5.0.9 on 2026-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, help_text='ที่อยู่ร้าน — พิมพ์บนใบเสร็จ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tax_id',
            field=models.CharField(blank=True, help_text='เลขประจำตัวผู้เสียภาษีอากร 13 หลัก — ต้องพิมพ์บนใบเสร็จตามกฎหมาย', max_length=20, null=True),
        ),
    ]
