# Generated by Django 5.0.9 on 2026-07-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_store_address_alter_store_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sync_key_hash',
            field=models.CharField(blank=True, help_text='hash ของ secret ที่ store-local backend ใช้ยืนยันตัวตนตอน sync ขึ้น cloud (ดู StoreSyncKeyAuthentication) — สร้าง/หมุนด้วย manage.py generate_store_sync_key', max_length=255, null=True),
        ),
    ]
