# Generated by Django 5.0.9 on 2026-07-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_store_sync_key_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='customer_order_base_url',
            field=models.URLField(blank=True, help_text='URL ที่ลูกค้าสแกน QR แล้วเข้าถึงเมนูสั่งอาหารเองได้ เช่น http://192.168.9.13:8080 (ต้องใส่ scheme และพอร์ตที่ถูกต้องของ nginx) — เว้นว่างได้ ถ้าไม่ตั้งค่า ระบบจะใช้ URL หน้าปัจจุบันของพนักงานตอนสร้าง QR แทน', null=True),
        ),
    ]
