# Generated by Django 5.0.9 on 2026-07-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_store_customer_order_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='device_id',
            field=models.CharField(default='POS01', help_text='prefix ใบเสร็จของเครื่อง POS (เช่น POS01) — ระบบรองรับเครื่อง POS เดียวต่อร้านเท่านั้น ถ้าร้านมีหลายเครื่องพร้อมกัน ห้ามใช้ค่านี้ตรงๆ เพราะเลขที่ใบเสร็จจะชนกัน', max_length=50),
        ),
    ]
