# Generated by Django 5.0.9 on 2026-07-24 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pin_code_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('OWNER', 'เจ้าของร้าน'), ('MANAGER', 'ผู้จัดการ'), ('CASHIER', 'แคชเชียร์'), ('SERVER', 'พนักงานเสิร์ฟ')], default='SERVER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenancy.store')),
            ],
        ),
    ]
