# Generated by Django 5.0.9 on 2026-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('tenancy', '0002_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='additional_stores',
            field=models.ManyToManyField(blank=True, related_name='owner_viewers', to='tenancy.store'),
        ),
    ]
