# Generated by Django 5.0.9 on 2026-07-24 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        ('menu', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'ทานที่ร้าน'), ('TAKEAWAY', 'กลับบ้าน')], default='DINE_IN', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'กำลังทาน'), ('PAID', 'ชำระเงินแล้ว'), ('CANCELLED', 'ยกเลิก')], default='OPEN', max_length=20)),
                ('session_token', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to='staff.staff')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_orders', to='staff.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenancy.store')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floor.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('kitchen_status', models.CharField(choices=[('PENDING', 'รอส่งครัว'), ('SENT', 'ส่งครัวแล้ว'), ('SERVED', 'เสิร์ฟแล้ว')], default='PENDING', max_length=20)),
                ('channel', models.CharField(choices=[('STAFF', 'พนักงานสั่งให้'), ('CUSTOMER', 'ลูกค้าสั่งเอง (QR/Barcode)')], default='STAFF', max_length=20)),
                ('is_takeaway', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modifiers', to='orders.orderitem')),
            ],
        ),
    ]
