# Generated by Django 5.0.9 on 2026-07-24 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ORDER_CANCELLED', 'ยกเลิกออเดอร์'), ('ORDER_ITEM_VOIDED', 'ลบรายการอาหารหลังส่งครัวแล้ว'), ('ORDER_DISCOUNT_APPLIED', 'ให้ส่วนลดออเดอร์'), ('TABLE_STATUS_OVERRIDE', 'แก้สถานะโต๊ะด้วยมือ'), ('MENU_PRICE_CHANGED', 'แก้ราคาเมนู'), ('MASTER_DATA_DEACTIVATED', 'Soft-delete master data'), ('STAFF_LOGIN_FAILED', 'ใส่ PIN ผิด'), ('SESSION_TOKEN_REJECTED', 'session_token หมดอายุ/ปิดแล้ว'), ('SYNC_CONFLICT_RESOLVED', 'Last-Write-Wins ทับข้อมูลเดิม'), ('SYNC_IDEMPOTENT_REJECT', 'push ซ้ำ UUID เดิม')], max_length=40)),
                ('device_id', models.CharField(max_length=50)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='staff.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenancy.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
